---
title: "Modelling II"
author: "BIOSCI220"
date: "Semester 1 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Learing Objectives

By the end of this lab student should be able to

   + Write R code to fit a linear model with interaction terms in the explanatory variables
   + Interpret estimated effects with reference to confidence intervals from linear regression models. Specifically the interpretation of
      + main effects in a model with an interaction
      + the effect of one variable when others are included in the model
   + Explain why you may want to include interaction effects in a linear model
   + Describe the differences between the operators : and * in an R model-fitting formula
   + Critique the fitted model

### Suggested reading


[Mueller, R. C., Scudder, C. M., Porter, M. E., Talbot Trotter III, R., Gehring, C. A., & Whitham, T. G. (2005). Differential tree mortality in response to severe drought: evidence for long‐term vegetation shifts. Journal of Ecology, 93(6), 1085-1093.](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/j.1365-2745.2005.01042.x)

## Interactions

## Model formulae

## Model checking

## Model comparison and selection

## Beyond Linear Models to Generalised Linear Models (GLMs)

Recall the assumptions of a linear model

+ The $i$th observation's response, $Y_i$, comes from a normal distribution
+ Its mean, $\mu_i$, is a linear combination of the explanatory terms
+ Its variance, $\sigma^2$, is the same for all observations
+ Each observation's response is independent of all others
  
But, what if we want to rid ourselves from a model with normal errors? 

The answer: Generalised Linear Models.

### Counting animals... 

A normal distribution does not adequately describe the response, the number of animals

 + It is a continuous distribution, but the response is discrete
 + It is symmetric, but the response is unlikely to be so
 + It is unbounded, and assumes it is plausible for the response to be negative


I addition, a linear regression model typically assumes constant variance, but int his situation this unlikely to be the case.

So why assume a normal distribution? Let's use a Poisson distribution instead.

\begin{equation*}    
    \mu_i = \beta_0 + \beta_1 x_i,
  \end{equation*}

So 
  \begin{equation*}
    Y_i \sim \text{Normal}(\mu_i\, \sigma^2),
  \end{equation*}
  
becomes
  
\begin{equation*}
    Y_i \sim \text{Poisson}(\mu_i),
\end{equation*}
  
The Poisson distribution is commonly used as a general-purpose distribution for counts. A key feature of this distribution is $\text{Var}(Y_i) = \mu_i$, so we expect the variance to increase with the mean.

Want to learn more then consider taking more [stats](https://www.calendar.auckland.ac.nz/en/courses/faculty-of-science/statistics.html?_ga=2.188381802.397158218.1586127105-552858658.1546562925) courses :)
  

## Lab work

Continue work on your Executive Summary (worth  18\% of your final grade). You are free to work through the material provided and your final report. You may work in groups, however, the final report must be your **own** work. Your Executive Summary should be no more than one A4 page. It should concisely effectively communicate your hypothesis, the statistical analysis undertaken, and your findings.