<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2 Data exploration and visualization | Module I BIOSCI220, University of Auckland</title>
  <meta name="description" content="2 Data exploration and visualization | Module I BIOSCI220, University of Auckland" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="2 Data exploration and visualization | Module I BIOSCI220, University of Auckland" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2 Data exploration and visualization | Module I BIOSCI220, University of Auckland" />
  
  
  

<meta name="author" content="Charlotte Jones-Todd" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="r-and-rstudio.html"/>

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#course-overview-biosci220"><i class="fa fa-check"></i><b>0.1</b> Course Overview: BIOSCI220</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#module-1-key-topics"><i class="fa fa-check"></i><b>0.2</b> Module 1: Key Topics</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#timetable-assessment-modules-i-ii-and-iii"><i class="fa fa-check"></i><b>0.3</b> Timetable &amp; Assessment (Modules I, II, and III)</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="r-and-rstudio.html"><a href="r-and-rstudio.html"><i class="fa fa-check"></i><b>1</b> <code>R</code> and <code>RStudio</code></a><ul>
<li class="chapter" data-level="1.1" data-path="r-and-rstudio.html"><a href="r-and-rstudio.html#learning-objectives"><i class="fa fa-check"></i><b>1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="1.2" data-path="r-and-rstudio.html"><a href="r-and-rstudio.html#introduction-to-r-and-rstudio"><i class="fa fa-check"></i><b>1.2</b> Introduction to <code>R</code> and <code>RStudio</code>?</a></li>
<li class="chapter" data-level="1.3" data-path="r-and-rstudio.html"><a href="r-and-rstudio.html#exploratory-data-analysis-eda"><i class="fa fa-check"></i><b>1.3</b> Exploratory Data Analysis (EDA)</a></li>
<li class="chapter" data-level="1.4" data-path="r-and-rstudio.html"><a href="r-and-rstudio.html#other-resources-optional-but-recommended"><i class="fa fa-check"></i><b>1.4</b> Other resources: optional but recommended</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-exploration-and-visualization.html"><a href="data-exploration-and-visualization.html"><i class="fa fa-check"></i><b>2</b> Data exploration and visualization</a><ul>
<li class="chapter" data-level="2.1" data-path="data-exploration-and-visualization.html"><a href="data-exploration-and-visualization.html#learning-objectives-1"><i class="fa fa-check"></i><b>2.1</b> Learning objectives</a></li>
<li class="chapter" data-level="2.2" data-path="data-exploration-and-visualization.html"><a href="data-exploration-and-visualization.html#data-wrangling-and-manipulation"><i class="fa fa-check"></i><b>2.2</b> Data wrangling and manipulation</a></li>
<li class="chapter" data-level="2.3" data-path="data-exploration-and-visualization.html"><a href="data-exploration-and-visualization.html#data-sovereignty"><i class="fa fa-check"></i><b>2.3</b> Data sovereignty</a></li>
<li class="chapter" data-level="2.4" data-path="data-exploration-and-visualization.html"><a href="data-exploration-and-visualization.html#data-viz"><i class="fa fa-check"></i><b>2.4</b> Data Viz</a></li>
<li class="chapter" data-level="2.5" data-path="data-exploration-and-visualization.html"><a href="data-exploration-and-visualization.html#other-resources-optional-but-recommended-1"><i class="fa fa-check"></i><b>2.5</b> Other resources: optional but recommended</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Module I BIOSCI220, University of Auckland</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data-exploration-and-visualization" class="section level1">
<h1><span class="header-section-number">2</span> Data exploration and visualization</h1>
<p>So now you've been introduced to <code>R</code> and <code>RStudio</code> let's get going with some data manipulation and visualization. Exploring and visualising your data is one of the most important steps. It's also one of the simplest!</p>
<p>You'll not find anyone who's not made the mistake of taking their data for granted. Just because someone says it's so <strong>NEVER</strong> trust that that's the case. From typos, to <code>NA</code>s, through <a href="https://stats.stackexchange.com/questions/225175/why-do-some-people-use-999-or-9999-to-replace-missing-values">-999</a> and let's not even talk dates, your data will always have a surprise in store for you.</p>
<div id="learning-objectives-1" class="section level2">
<h2><span class="header-section-number">2.1</span> Learning objectives</h2>
<ul>
<li>Carry out and interpret the outputs of basic exploratory data analysis using in-built R functions</li>
<li>Define data sovereignty and explain this in relation to a researcher's obligation when collecting, displaying, and analysing data</li>
<li>Create and communicate informative data visualisations using <code>R</code></li>
<li>Discuss and critique data visualisations</li>
</ul>
</div>
<div id="data-wrangling-and-manipulation" class="section level2">
<h2><span class="header-section-number">2.2</span> Data wrangling and manipulation</h2>
<p><strong><code>tidy</code> data</strong></p>
<div class="figure">
<img src="https://raw.githubusercontent.com/allisonhorst/stats-illustrations/master/rstats-artwork/tidydata_1.jpg" style="width:70.0%" />

</div>
<p>Illustration from the Openscapes blog <a href="https://www.openscapes.org/blog/2020/10/12/tidy-data/">Tidy Data for reproducibility, efficiency, and collaboration</a> by Julia Lowndes and Allison Horst</p>
<div id="introuducing-the-palmer-penguins" class="section level3">
<h3><span class="header-section-number">2.2.1</span> Introuducing the <a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0090081">Palmer penguins</a></h3>
<iframe src="https://giphy.com/embed/3og0IO5z8Rd30ktV6g" width="40%" height="400px" style="border: none;">
</iframe>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(palmerpenguins) ## contains some nice penguin data
penguins</code></pre></div>
<pre><code>## # A tibble: 344 x 8
##    species island bill_length_mm bill_depth_mm flipper_length_… body_mass_g
##    &lt;fct&gt;   &lt;fct&gt;           &lt;dbl&gt;         &lt;dbl&gt;            &lt;int&gt;       &lt;int&gt;
##  1 Adelie  Torge…           39.1          18.7              181        3750
##  2 Adelie  Torge…           39.5          17.4              186        3800
##  3 Adelie  Torge…           40.3          18                195        3250
##  4 Adelie  Torge…           NA            NA                 NA          NA
##  5 Adelie  Torge…           36.7          19.3              193        3450
##  6 Adelie  Torge…           39.3          20.6              190        3650
##  7 Adelie  Torge…           38.9          17.8              181        3625
##  8 Adelie  Torge…           39.2          19.6              195        4675
##  9 Adelie  Torge…           34.1          18.1              193        3475
## 10 Adelie  Torge…           42            20.2              190        4250
## # … with 334 more rows, and 2 more variables: sex &lt;fct&gt;, year &lt;int&gt;</code></pre>
<p>So, what does this show us?</p>
<ul>
<li><code>A tibble: 344 x 8</code>: A <code>tibble</code> is a specific kind of data frame in <code>R</code>. The <code>penguin</code> dataset has</li>
<li><code>344</code> rows (i.e., 344 different observations). Here, each observation corresponds to a penguin.</li>
<li><code>8</code> columns corresponding to 3 variables describing each observation.</li>
<li><code>species</code>, <code>island</code>, <code>bill_length_mm</code>, <code>bill_depth_mm</code>, <code>flipper_length_mm</code>, <code>body_mass_g</code>, <code>sex</code>, and <code>year</code> are the different variables of this dataset.</li>
<li>We then have a preview of the first 10 rows of observations corresponding to the first 10 penguins. ``<code>... with 334 more rows</code> indicates there are 334 more rows to see, but these have not been printed (likely as it would clog our screen)</li>
</ul>
<p>To learn more about the penguins read the <a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0090081">paper that talks all about the data collection.</a></p>
</div>
<div id="common-dataframe-manipulations-in-the-tidyverse-using-dplyr-and-tidyr" class="section level3">
<h3><span class="header-section-number">2.2.2</span> Common dataframe manipulations in the <code>tidyverse</code>, using <code>dplyr</code> and <code>tidyr</code></h3>
<p>Even from these first few rows of data we can see that there are some <code>NA</code> values. Let's count the number of <code>NA</code>s. Remember the <code>%&gt;%</code> operator? Here we're going to be introduced to a few new things</p>
<ul>
<li>the <code>apply()</code> function,</li>
<li>the <code>is.na()</code> function, and</li>
<li>how <code>R</code> deals with <code>logical</code> values!</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)
penguins <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">apply</span>(.,<span class="dv">2</span>,is.na) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">apply</span>(.,<span class="dv">2</span>,sum)</code></pre></div>
<pre><code>##           species            island    bill_length_mm     bill_depth_mm 
##                 0                 0                 2                 2 
## flipper_length_mm       body_mass_g               sex              year 
##                 2                 2                11                 0</code></pre>
<p>There's lot going on in that code! Let's break it down</p>
<ul>
<li>Take <code>penguins</code> then</li>
<li>Use <code>penguins</code> as an input to the <code>apply()</code> function (this is specified as the first argument using the <code>.</code>)</li>
<li>Now the <code>apply()</code> function takes 3 arguments:
<ol style="list-style-type: decimal">
<li>the data object you want it to <em>apply</em> something to (in our case <code>penguins</code>)</li>
<li>the margin you want to <em>apply</em> that something to; 1 stands for rows and 2 stands for columns, and</li>
<li>the function you want it to apply (in our case <code>is.na()</code>).</li>
</ol></li>
<li>So the second line of code is asking <code>R</code> to <em>apply</em> the <code>is.na()</code> function over the columns of <code>penguins</code>
<ul>
<li><code>is.na()</code> asks for each value it's fed is it an <code>NA</code> value; it returens a <code>TRUE</code> if so and a <code>FALSE</code> otherwise</li>
</ul></li>
<li>The output from the first <code>apply()</code> is then fed to the second <code>apply()</code> (using the <code>.</code>). The <code>sum()</code> function then add them up!
<ul>
<li><code>R</code> treats a <code>TRUE</code> as a 1 and a <code>FALSE</code> as a 0.</li>
</ul></li>
</ul>
<p>So how many <code>NA</code>s do you think there are!</p>
<p>Doesn't help much. To</p>
<p>Now we know there are <code>NA</code> values throughout the data let's remove then and create a new <code>NA</code> free version called <code>penguins_nafree</code>. There is a really handy <code>tidyverse</code> (<code>dplyr</code>) function for this!</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">penguins_nafree &lt;-<span class="st"> </span>penguins <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">drop_na</span>()
penguins_nafree</code></pre></div>
<pre><code>## # A tibble: 333 x 8
##    species island bill_length_mm bill_depth_mm flipper_length_… body_mass_g
##    &lt;fct&gt;   &lt;fct&gt;           &lt;dbl&gt;         &lt;dbl&gt;            &lt;int&gt;       &lt;int&gt;
##  1 Adelie  Torge…           39.1          18.7              181        3750
##  2 Adelie  Torge…           39.5          17.4              186        3800
##  3 Adelie  Torge…           40.3          18                195        3250
##  4 Adelie  Torge…           36.7          19.3              193        3450
##  5 Adelie  Torge…           39.3          20.6              190        3650
##  6 Adelie  Torge…           38.9          17.8              181        3625
##  7 Adelie  Torge…           39.2          19.6              195        4675
##  8 Adelie  Torge…           41.1          17.6              182        3200
##  9 Adelie  Torge…           38.6          21.2              191        3800
## 10 Adelie  Torge…           34.6          21.1              198        4400
## # … with 323 more rows, and 2 more variables: sex &lt;fct&gt;, year &lt;int&gt;</code></pre>
<p>Below are some other useful manipulation functions; have a look at the out puts and run them yourselves and see if you can work out what they're doing.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">filter</span>(penguins_nafree, island <span class="op">==</span><span class="st"> &quot;Torgersen&quot;</span> )</code></pre></div>
<pre><code>## # A tibble: 47 x 8
##    species island bill_length_mm bill_depth_mm flipper_length_… body_mass_g
##    &lt;fct&gt;   &lt;fct&gt;           &lt;dbl&gt;         &lt;dbl&gt;            &lt;int&gt;       &lt;int&gt;
##  1 Adelie  Torge…           39.1          18.7              181        3750
##  2 Adelie  Torge…           39.5          17.4              186        3800
##  3 Adelie  Torge…           40.3          18                195        3250
##  4 Adelie  Torge…           36.7          19.3              193        3450
##  5 Adelie  Torge…           39.3          20.6              190        3650
##  6 Adelie  Torge…           38.9          17.8              181        3625
##  7 Adelie  Torge…           39.2          19.6              195        4675
##  8 Adelie  Torge…           41.1          17.6              182        3200
##  9 Adelie  Torge…           38.6          21.2              191        3800
## 10 Adelie  Torge…           34.6          21.1              198        4400
## # … with 37 more rows, and 2 more variables: sex &lt;fct&gt;, year &lt;int&gt;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summarise</span>(penguins_nafree, <span class="dt">avgerage_bill_length =</span> <span class="kw">mean</span>(bill_length_mm))</code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   avgerage_bill_length
##                  &lt;dbl&gt;
## 1                 44.0</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">group_by</span>(penguins_nafree, species)</code></pre></div>
<pre><code>## # A tibble: 333 x 8
## # Groups:   species [3]
##    species island bill_length_mm bill_depth_mm flipper_length_… body_mass_g
##    &lt;fct&gt;   &lt;fct&gt;           &lt;dbl&gt;         &lt;dbl&gt;            &lt;int&gt;       &lt;int&gt;
##  1 Adelie  Torge…           39.1          18.7              181        3750
##  2 Adelie  Torge…           39.5          17.4              186        3800
##  3 Adelie  Torge…           40.3          18                195        3250
##  4 Adelie  Torge…           36.7          19.3              193        3450
##  5 Adelie  Torge…           39.3          20.6              190        3650
##  6 Adelie  Torge…           38.9          17.8              181        3625
##  7 Adelie  Torge…           39.2          19.6              195        4675
##  8 Adelie  Torge…           41.1          17.6              182        3200
##  9 Adelie  Torge…           38.6          21.2              191        3800
## 10 Adelie  Torge…           34.6          21.1              198        4400
## # … with 323 more rows, and 2 more variables: sex &lt;fct&gt;, year &lt;int&gt;</code></pre>
<p>Often we want to summarise variables by different groups (factors). Below we</p>
<ul>
<li>Take the <code>penguins_nafree</code> data then</li>
<li>Use this and apply the <code>group_by()</code> function to group by <code>species</code></li>
<li>Use this output and apply the <code>summarize()</code> function to calculate the mean (using (<code>mean()</code>) bill length (<code>bill_length_mm</code>) of each group (<code>species</code>), calling the resulting number <code>avgerage_bill_length</code></li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">penguins_nafree <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(species) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">avgerage_bill_length =</span> <span class="kw">mean</span>(bill_length_mm))</code></pre></div>
<pre><code>## # A tibble: 3 x 2
##   species   avgerage_bill_length
## * &lt;fct&gt;                    &lt;dbl&gt;
## 1 Adelie                    38.8
## 2 Chinstrap                 48.8
## 3 Gentoo                    47.6</code></pre>
<p>We can also group by multiple factors, for example,</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">penguins_nafree <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(island,species) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">avgerage_bill_length =</span> <span class="kw">mean</span>(bill_length_mm))</code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;island&#39;. You can override using the `.groups` argument.</code></pre>
<pre><code>## # A tibble: 5 x 3
## # Groups:   island [3]
##   island    species   avgerage_bill_length
##   &lt;fct&gt;     &lt;fct&gt;                    &lt;dbl&gt;
## 1 Biscoe    Adelie                    39.0
## 2 Biscoe    Gentoo                    47.6
## 3 Dream     Adelie                    38.5
## 4 Dream     Chinstrap                 48.8
## 5 Torgersen Adelie                    39.0</code></pre>
</div>
</div>
<div id="data-sovereignty" class="section level2">
<h2><span class="header-section-number">2.3</span> Data sovereignty</h2>
<p><a href="https://en.wikipedia.org/wiki/Data_sovereignty">''<strong>Data sovereignty</strong> is the idea that data are subject to the laws and governance structures within the nation it is collected''</a></p>
</div>
<div id="data-viz" class="section level2">
<h2><span class="header-section-number">2.4</span> Data Viz</h2>
<blockquote>
<p>&quot;...have obligations in that we have a great deal of power over how people ultimately make use of data, both in the patterns they see and the conclusions they draw.&quot;</p>
</blockquote>
<blockquote>
<footer>
--- Michael Correll, Ethical Dimensions of Visualization Research
</footer>
</blockquote>
<blockquote>
<p>&quot;Clutter and confusion are not attributes of data - they are shortcomings of design.&quot;</p>
</blockquote>
<blockquote>
<footer>
--- Edward Tufte
</footer>
</blockquote>
<div id="two-types-of-plots" class="section level3">
<h3><span class="header-section-number">2.4.1</span> Two types of plots</h3>
<ol style="list-style-type: decimal">
<li><strong>For you</strong></li>
</ol>
<ul>
<li>data exploration</li>
<li>doesn't have to look pretty</li>
<li>just needs to get to the point</li>
</ul>
<p><img src="_main_files/figure-html/example,%20me-1.png" width="672" /><img src="_main_files/figure-html/example,%20me-2.png" width="672" /></p>
<ol start="2" style="list-style-type: decimal">
<li><strong>For others</strong></li>
</ol>
<ul>
<li>clear purpose</li>
<li>designed for the audience</li>
<li>make it easy to read (<em>this covers a lot of things</em>)</li>
<li>do not distort</li>
</ul>
<div class="figure">
<img src="https://jimgruman.netlify.app/post/variableimportance/2020_31_PalmerPenguins.png" />

</div>
<p>Plots by Cedric Scherer and mentioned on <a href="https://jimgruman.netlify.app/post/variableimportance/">this blog</a></p>
<p>So we've seen some pretty plots, let's get around to making some!</p>
</div>
<div id="introducing-ggplot2" class="section level3">
<h3><span class="header-section-number">2.4.2</span> Introducing <code>ggplot2</code></h3>
<p><code>ggplot2</code> is an <code>R</code> package for producing statistical, or data, graphics; it has an underlying grammar based on the <a href="https://www.amazon.com/Grammar-Graphics-Statistics-Computing/dp/0387245448">Grammar of Graphics</a></p>
<p>Every <code>ggplot2</code> plot has three key components:</p>
<ul>
<li><p><code>data</code>,</p></li>
<li><p>A set of <code>aes</code>thetic mappings between variables in the data and visual properties, and</p></li>
<li><p>At least one layer which describes how to render each observation. Layers are usually created with a <code>geom</code> function.</p></li>
</ul>
<div id="plotting-palmerpenguins" class="section level4">
<h4><span class="header-section-number">2.4.2.1</span> Plotting <code>palmerpenguins</code></h4>
<p><strong>You might find <a href="https://cmjt.shinyapps.io/penguin/">this application</a> useful, now and later...</strong></p>
<p>We've seen that there are three <code>factor</code> variables in the dataset: <code>species</code>, <code>island</code>, and <code>sex</code>. To count the number of penguins of each <code>species</code> and <code>sex</code> on each <code>island</code> we could use</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">penguins_nafree <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">count</span>(species, sex, island)</code></pre></div>
<pre><code>## # A tibble: 10 x 4
##    species   sex    island        n
##    &lt;fct&gt;     &lt;fct&gt;  &lt;fct&gt;     &lt;int&gt;
##  1 Adelie    female Biscoe       22
##  2 Adelie    female Dream        27
##  3 Adelie    female Torgersen    24
##  4 Adelie    male   Biscoe       22
##  5 Adelie    male   Dream        28
##  6 Adelie    male   Torgersen    23
##  7 Chinstrap female Dream        34
##  8 Chinstrap male   Dream        34
##  9 Gentoo    female Biscoe       58
## 10 Gentoo    male   Biscoe       61</code></pre>
<p>Not too easy to compare the numbers here; what about a bar graph (<code>geom_bar()</code>)? Based on what we went throuh in the lecture see if you can figure out what each line is adding to the plot. What do you think <code>facet_wrap()</code> is doing? To figure it out run the code yourself and try changing some of the lines of code.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(penguins_nafree, <span class="kw">aes</span>(<span class="dt">x =</span> species, <span class="dt">fill =</span> sex)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_bar</span>(<span class="dt">alpha =</span> <span class="fl">0.8</span>, <span class="dt">position =</span> <span class="st">&quot;dodge&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>island) <span class="op">+</span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_linedraw</span>() <span class="op">+</span><span class="st"> </span>## remember themes...
<span class="st">  </span><span class="kw">scale_fill_manual</span>(<span class="dt">values =</span> <span class="kw">c</span>(<span class="st">&quot;cyan4&quot;</span>,<span class="st">&quot;darkorange&quot;</span>), <span class="dt">name =</span> <span class="st">&quot;Sex&quot;</span>) </code></pre></div>
<p><img src="_main_files/figure-html/bar-1.png" width="672" /></p>
<p>We aslo saw there were a few continuous variables, so let's look at scatter plots (<code>geom_point()</code>).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> penguins_nafree, <span class="kw">aes</span>(<span class="dt">x =</span> bill_length_mm, <span class="dt">y =</span> bill_depth_mm)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">color =</span> species),<span class="dt">size =</span> <span class="dv">2</span>)  <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_color_manual</span>(<span class="dt">values =</span> <span class="kw">c</span>(<span class="st">&quot;darkorange&quot;</span>,<span class="st">&quot;darkorchid&quot;</span>,<span class="st">&quot;cyan4&quot;</span>), <span class="dt">name =</span> <span class="st">&quot;&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_bw</span>() <span class="op">+</span><span class="st"> </span>## Oo a new theme
<span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Bill length (mm)&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;Bill length (mm)&quot;</span>)</code></pre></div>
<p><img src="_main_files/figure-html/point-1.png" width="672" /></p>
<p>What about the <em>spread</em>/<em>distribution</em> of our continuous vaiables by the factor variables (e.g., <code>species</code>):</p>
<ul>
<li>Boxplots (<code>geom_boxplot()</code>)?</li>
<li>Violin plots (<code>geom_violin()</code>)?</li>
<li>Histograms (<code>geom_histogram()</code>)?</li>
</ul>
<p>In addition,we should always avoid using similarily bight red and green colours: they may not be distinguishable for red-green colorblind readers. Using <code>ggplot2</code> we can access a whole range of colourblind friendly palettes: one package that has a whole range is <code>RColorBrewer</code> install it then try running <code>RColorBrewer::display.brewer.all(colorblindFriendly = TRUE)</code> what do you think you've asked your compueter to show you?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## boxplot
<span class="kw">ggplot</span>(penguins_nafree,<span class="kw">aes</span>(<span class="dt">x =</span> species, <span class="dt">y =</span> flipper_length_mm)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_boxplot</span>() <span class="op">+</span>
<span class="st">    </span><span class="kw">ylab</span>(<span class="st">&quot;Flipper length (mm)&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">xlab</span>(<span class="st">&quot;&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_classic</span>() ## yet another theme</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## violin plot
<span class="kw">ggplot</span>(penguins_nafree,<span class="kw">aes</span>(<span class="dt">x =</span> species, <span class="dt">y =</span> flipper_length_mm)) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">geom_violin</span>() <span class="op">+</span>
<span class="st">    </span><span class="kw">ylab</span>(<span class="st">&quot;Flipper length (mm)&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">xlab</span>(<span class="st">&quot;&quot;</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">theme_minimal</span>() ## soon you could be making your own</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-16-2.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## histogram, with a colorblind friendly palette
## try running display.brewer.all(colorblindFriendly = TRUE)
## what do you think it&#39;s doing
<span class="kw">ggplot</span>(penguins_nafree,<span class="kw">aes</span>(<span class="dt">x =</span> flipper_length_mm)) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">fill =</span> species), <span class="dt">alpha =</span> <span class="fl">0.5</span>, <span class="dt">position =</span> <span class="st">&quot;identity&quot;</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">xlab</span>(<span class="st">&quot;Flipper length (mm)&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">scale_fill_brewer</span>(<span class="dt">palette =</span> <span class="st">&quot;Dark2&quot;</span>, <span class="dt">name =</span> <span class="st">&quot;Species&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_light</span>()</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-16-3.png" width="672" /></p>
</div>
<div id="what-do-we-think-about-when-we-look-at-plots" class="section level4">
<h4><span class="header-section-number">2.4.2.2</span> What do we think about when we look at plots</h4>
<p>Between group variation</p>
<p><img src="_main_files/figure-html/unnamed-chunk-17-1.png" width="672" /> Within group variation</p>
<p><img src="_main_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
</div>
</div>
</div>
<div id="other-resources-optional-but-recommended-1" class="section level2">
<h2><span class="header-section-number">2.5</span> Other resources: optional but recommended</h2>
<ul>
<li><a href="https://www.onenet.co.nz/our-resources/why-data-sovereignty-matters/">Why data sovereignty matters</a></li>
<li><a href="https://library.oapen.org/handle/20.500.12657/42782">Indigenous Data Sovereignty and Policy</a></li>
<li><a href="https://cdn.auckland.ac.nz/assets/psych/about/our-research/documents/TMR%2BM%C4%81ori%2BData%2BSovereignty%2BPrinciples%2BOct%2B2018.pdf">Principles of Māori Data Sovereignty</a></li>
<li><a href="https://rstudio.com/wp-content/uploads/2016/11/ggplot2-cheatsheet-2.1.pdf"><code>ggplot2</code> cheatsheet</a></li>
<li><a href="https://ggplot2-book.org/introduction.html">Elegant Graphics for Data Analysis</a></li>
<li><a href="https://ourcodingclub.github.io/tutorials/datavis/">Using <code>ggplot2</code> to communicate your results</a></li>
<li><a href="https://tinystats.github.io/teacups-giraffes-and-statistics/">Teacups, giraffes, and statistics: free online introductory level R and statistics modules</a></li>
</ul>

</div>
</div>






            </section>

          </div>
        </div>
      </div>
<a href="r-and-rstudio.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
